import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#2f3034",
        "inverse-surface": "#e3e2e6",
        "tertiary-container": "#ff5636",
        "tertiary-fixed": "#ffdad3",
        "surface-container-lowest": "#0d0e11",
        "secondary-fixed-dim": "#60dda3",
        "surface-container-high": "#292a2d",
        "on-primary-fixed": "#001a43",
        "surface-dim": "#121316",
        outline: "#8c909f",
        "on-tertiary-fixed": "#3e0400",
        "on-secondary": "#003823",
        "primary-fixed": "#d9e2ff",
        "on-surface": "#e3e2e6",
        "on-secondary-container": "#00311e",
        "on-secondary-fixed-variant": "#005235",
        "surface-container-highest": "#343538",
        "primary-container": "#528dff",
        background: "#121316",
        error: "#ffb4ab",
        "surface-container": "#1f1f23",
        "inverse-primary": "#0059c6",
        "primary-fixed-dim": "#afc6ff",
        "on-error": "#690005",
        "on-secondary-fixed": "#002113",
        "on-primary-container": "#00275f",
        "surface-variant": "#343538",
        "surface-container-low": "#1b1b1f",
        secondary: "#60dda3",
        primary: "#afc6ff",
        "tertiary-fixed-dim": "#ffb4a5",
        "on-background": "#e3e2e6",
        "on-surface-variant": "#c2c6d6",
        "on-primary": "#002d6c",
        "outline-variant": "#424753",
        "surface-bright": "#38393c",
        surface: "#121316",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#004398",
        tertiary: "#ffb4a5",
        "on-tertiary": "#650b00",
        "on-tertiary-container": "#580900",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#7efabd",
        "surface-tint": "#afc6ff",
        "secondary-container": "#14a570",
        "on-tertiary-fixed-variant": "#8e1400",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "monospace"],
      },
    },
  },
  plugins: [],
};

export default config;
